# docker-compose.yml
version: '3.8'

services:
  blockchain_app:
    build:
      context: .  # Le Dockerfile est dans le répertoire courant
    ports:
      - "3000:3000"  # Expose le port 3000 du conteneur au port 3000 de l'hôte
    container_name: blockchain_app
    restart: always  # Redémarre automatiquement le conteneur en cas de crash ou de redémarrage
    environment:
      - NODE_ENV=production